//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCacDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOCONGNODAILY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAOCAOCONGNODAILY()
        {
            this.CHITIETBAOCAOCONGNOes = new HashSet<CHITIETBAOCAOCONGNO>();
        }
    
        public string MABAOCAOCONGNO { get; set; }
        public System.DateTime THANGBAOCAO { get; set; }
        public double TONGDONGIA { get; set; }
        public double TONGTIENDATHANHTOAN { get; set; }
        public double NOCU { get; set; }
        public double TONGTIENNO { get; set; }
        public string MADAILY { get; set; }
    
        public virtual DAILY DAILY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBAOCAOCONGNO> CHITIETBAOCAOCONGNOes { get; set; }
    }
}
