//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCacDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOTHUCHI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAOCAOTHUCHI()
        {
            this.CHITIETBAOCAOCHIs = new HashSet<CHITIETBAOCAOCHI>();
            this.PHIEUTHUTIENs = new HashSet<PHIEUTHUTIEN>();
        }
    
        public string MABAOCAOTHUCHI { get; set; }
        public System.DateTime NGAYBAOCAO { get; set; }
        public double TONGCHI { get; set; }
        public double TONGTHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBAOCAOCHI> CHITIETBAOCAOCHIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHUTIEN> PHIEUTHUTIENs { get; set; }
    }
}
