//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCacDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAODOANHTHU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAOCAODOANHTHU()
        {
            this.CHITIETBAOCAODOANHTHUs = new HashSet<CHITIETBAOCAODOANHTHU>();
        }
    
        public string MABAOCAODOANHTHU { get; set; }
        public System.DateTime THANG { get; set; }
        public double TONGDOANHTHU { get; set; }
        public string MADAILY { get; set; }
    
        public virtual DAILY DAILY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBAOCAODOANHTHU> CHITIETBAOCAODOANHTHUs { get; set; }
    }
}
