//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCacDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETBAOCAOCONGNO
    {
        public string MACHITIETBCCONGNO { get; set; }
        public int SOLUONG { get; set; }
        public string MABAOCAOCONGNO { get; set; }
        public string MAHANGHOA { get; set; }
    
        public virtual BAOCAOCONGNODAILY BAOCAOCONGNODAILY { get; set; }
        public virtual HANGHOA HANGHOA { get; set; }
    }
}
