//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCacDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUXUATHANG
    {
        public string MACHITIETPHIEUXUATHANG { get; set; }
        public int SOLUONGXUAT { get; set; }
        public double BANGGIA { get; set; }
        public string MAPHIEUXUATHANG { get; set; }
        public string MAHANGHOA { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual PHIEUXUATHANG PHIEUXUATHANG { get; set; }
    }
}
