//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCacDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAILY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAILY()
        {
            this.BAOCAOCONGNODAILies = new HashSet<BAOCAOCONGNODAILY>();
            this.BAOCAODOANHTHUs = new HashSet<BAOCAODOANHTHU>();
            this.PHIEUTHUTIENs = new HashSet<PHIEUTHUTIEN>();
            this.PHIEUXUATHANGs = new HashSet<PHIEUXUATHANG>();
        }
    
        public string MADAILY { get; set; }
        public string TENDAILY { get; set; }
        public string TENCHUDAILY { get; set; }
        public string DIACHI { get; set; }
        public string SODIENTHOAI { get; set; }
        public System.DateTime NGAYTIEPNHAN { get; set; }
        public System.DateTime NGAYHDGAN { get; set; }
        public double DIEM { get; set; }
        public double TIENNO { get; set; }
        public string MAQUAN { get; set; }
        public string MAUUDAITHANHVIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAOCONGNODAILY> BAOCAOCONGNODAILies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAODOANHTHU> BAOCAODOANHTHUs { get; set; }
        public virtual QUAN QUAN { get; set; }
        public virtual UUDAITHANHVIEN UUDAITHANHVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHUTIEN> PHIEUTHUTIENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUXUATHANG> PHIEUXUATHANGs { get; set; }
    }
}
