//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCacDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANGHOA()
        {
            this.CHITIETBAOCAOCHIs = new HashSet<CHITIETBAOCAOCHI>();
            this.CHITIETBAOCAOCONGNOes = new HashSet<CHITIETBAOCAOCONGNO>();
            this.CHITIETBAOCAODOANHTHUs = new HashSet<CHITIETBAOCAODOANHTHU>();
            this.CHITIETPHIEUNHAPKHOes = new HashSet<CHITIETPHIEUNHAPKHO>();
            this.CHITIETPHIEUXUATHANGs = new HashSet<CHITIETPHIEUXUATHANG>();
        }
    
        public string MAHANGHOA { get; set; }
        public string TENHANGHOA { get; set; }
        public int SOLUONGCONLAI { get; set; }
        public double DONGIA { get; set; }
        public string MADONVITINH { get; set; }
        public string MAUUDAIHANGHOA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBAOCAOCHI> CHITIETBAOCAOCHIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBAOCAOCONGNO> CHITIETBAOCAOCONGNOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBAOCAODOANHTHU> CHITIETBAOCAODOANHTHUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAPKHO> CHITIETPHIEUNHAPKHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUXUATHANG> CHITIETPHIEUXUATHANGs { get; set; }
        public virtual DONVITINH DONVITINH { get; set; }
        public virtual UUDAIHANGHOA UUDAIHANGHOA { get; set; }
    }
}
