//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCacDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUXUATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUXUATHANG()
        {
            this.CHITIETPHIEUXUATHANGs = new HashSet<CHITIETPHIEUXUATHANG>();
        }
    
        public string MAPHIEUXUATHANG { get; set; }
        public System.DateTime NGAYXUATPHIEU { get; set; }
        public double TONGTIEN { get; set; }
        public double TONGPHAITRA { get; set; }
        public double KHACHTRA { get; set; }
        public double TIENCONDU { get; set; }
        public string MADAILY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUXUATHANG> CHITIETPHIEUXUATHANGs { get; set; }
        public virtual DAILY DAILY { get; set; }
    }
}
