//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCacDaiLy.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLCacDaiLyEntities : DbContext
    {
        public QLCacDaiLyEntities()
            : base("name=QLCacDaiLyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAOCAOCONGNODAILY> BAOCAOCONGNODAILies { get; set; }
        public virtual DbSet<BAOCAODOANHTHU> BAOCAODOANHTHUs { get; set; }
        public virtual DbSet<BAOCAOTHUCHI> BAOCAOTHUCHIs { get; set; }
        public virtual DbSet<CHITIETBAOCAOCHI> CHITIETBAOCAOCHIs { get; set; }
        public virtual DbSet<CHITIETBAOCAOCONGNO> CHITIETBAOCAOCONGNOes { get; set; }
        public virtual DbSet<CHITIETBAOCAODOANHTHU> CHITIETBAOCAODOANHTHUs { get; set; }
        public virtual DbSet<CHITIETPHIEUNHAPKHO> CHITIETPHIEUNHAPKHOes { get; set; }
        public virtual DbSet<CHITIETPHIEUXUATHANG> CHITIETPHIEUXUATHANGs { get; set; }
        public virtual DbSet<DAILY> DAILies { get; set; }
        public virtual DbSet<DONVITINH> DONVITINHs { get; set; }
        public virtual DbSet<HANGHOA> HANGHOAs { get; set; }
        public virtual DbSet<PHIEUNHAPKHO> PHIEUNHAPKHOes { get; set; }
        public virtual DbSet<PHIEUTHUTIEN> PHIEUTHUTIENs { get; set; }
        public virtual DbSet<PHIEUXUATHANG> PHIEUXUATHANGs { get; set; }
        public virtual DbSet<QUAN> QUANs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UUDAIHANGHOA> UUDAIHANGHOAs { get; set; }
        public virtual DbSet<UUDAITHANHVIEN> UUDAITHANHVIENs { get; set; }
    }
}
